### ISSUE TITLE
Contributors

### ISSUE THREAD

**Issue by CCChenhao997** [CCChenhao997/Multi-Granularity-Comment-Analysis#1]
@all-contributors Please add @airflier for his contributions.

**Comment by CCChenhao997** [comment]
@all-contributors Please add @airflier for his contributions.

**Comment by CCChenhao997** [comment]
@all-contributors Please add @airflier for code contribution.

**Comment by airflier** [comment]
@all-contributors Please add @CCChenhao997  for his contributions.

**Comment by airflier** [comment]
@all-contributors Please add @CCChenhao997  for ideas contribution.
